name: PullRequest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build ${{ matrix.example }}
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: lite/examples/${{ matrix.example }}/android
    strategy:
      fail-fast: false
      matrix:
        java_version: [ 11.0.3 ]
        example: [ smart_reply ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.1
      - name: Bazel install
        run: |
          brew tap bazelbuild/tap
          brew extract bazel bazelbuild/tap --version 3.0.0
          brew install bazel@3.0.0
      - name: Bazel build
        run: cd app && bazel build libs/cc:smartreply_runtime_aar
      - name: Build project
        run: ./gradlew assembleDebug
