name: PullRequest

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build ${{ matrix.example }}
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: lite/examples/${{ matrix.example }}/android
    strategy:
      fail-fast: false
      matrix:
        java_version: [ 11 ]
        example: [ hand_tracking, bert_qa, digit_classifier, gesture_classification, image_classification, image_segmentation, model_personalization, object_detection, posenet, recommendation, smart_reply, sound_classification, speech_commands, style_transfer, super_resolution, text_classification ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.1
      - name: Build project
        run: ./gradlew assembleDebug
