name: "Validate Gradle"
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lite/examples/${{ matrix.example }}
    strategy:
      matrix:
        java_version: [ 11 ]
        example: [ audio_classification, gesture_classification, model_personalization, posenet, super_resolution, bert_qa, object_detection, recommendation, text_classification, image_classification, optical_character_recognition, reinforcement_learning, text_searcher, digit_classifier, image_segmentation, pose_estimation, smart_reply, style_transfer, video_classification ]
    steps:
      - uses: actions/checkout@v3.4.0
      - uses: gradle/wrapper-validation-action@v1
